### ISSUE TITLE
StackCollectionViewLayout loop?

### ISSUE THREAD

**Issue by uzman** [jVirus/uicollectionview-layouts-kit#10]
Hi,
Is it possible to loop stackviewlayout?

**Comment by jVirus** [comment]
Hi, I assume this a duplicate issue. Please continue in the #9. Thanks

**Comment by uzman** [comment]
This is not the same question.
I want to make infinite loop with stackcollectionviewlayout.
I want users can always swipe from 0-to last.
Is it possible?

**Comment by jVirus** [comment]
Yeah, that is possible

**Comment by uzman** [comment]
So, how can make it infinite loop?

**Comment by jVirus** [comment]
The data source can be looped when swiping between the cells. As a backing data structure, the `circle buffer` can be used. Another approach is to implement a slightly modified version of the `Stack Collection View Layout`. Where, instead the layout attributes are circled in a similar manner as in the `circle buffer` data structure.
