### ISSUE TITLE
Size issue

### ISSUE THREAD

**Issue by Abhishekg219** [jVirus/uicollectionview-layouts-kit#5]
It does not support when images are loading from an API server.
Checked for Pinterest and Insta grid layout.

**Comment by jVirus** [comment]
Hello,

Can you please describe more thoroughly an issue that you are experiencing? 

You named the issue “size issues” then you say that “it does not support when images are loading from an API server”. Well, indeed there is no support for loading images from an API server, the repo provides only layouts for UICollectionView UI component. Again, please describe you issue step by step, so I will be able understand exactly what you mean and be able to reproduce it. Thanks!

**Comment by jVirus** [comment]
Upd. 

I thoroughly described

**Comment by jVirus** [comment]
It's been a while and there is no response. I'm going to close this issue, however if you decide to answer, then please don't open a new issue, just leave your response here. 

Thanks!
